### ISSUE TITLE
Where to load the dataset?

### ISSUE THREAD

**Issue by myh12138** [Yuxiang1995/ICDAR2021_MFD#1]
can you give a url?

**Comment by Yuxiang1995** [comment]
> can you give a url?

We are uploading dataset to the cloud disk, I will reply you as soon as the upload is completed

**Comment by Yuxiang1995** [comment]
> can you give a url?

http://transcriptorium.eu/~htrcontest/MathsICDAR2021/MFD2021/
You can download the dataset from this URL, before that you need to register an account follow the chapter **Registration and access to data** in http://transcriptorium.eu/~htrcontest/MathsICDAR2021/
It is a private dataset provided by sponsor, so I have no right to upload it to the cloud.

**Comment by myh12138** [comment]
the e-mail need these message ,but I don't  join in this competition，can you provide some fellow information for me,thanks. 
Group name and acronym
Institution
Participants and e-mail
Contact person

**Comment by delveintodetail** [comment]
@myh12138 
Pls send email to jandreu@prhlt.upv.es to ask for data access.

**Comment by Yuxiang1995** [comment]
> the e-mail need these message ,but I don't join in this competition，can you provide some fellow information for me,thanks.
> Group name and acronym
> Institution
> Participants and e-mail
> Contact person

you can register now by sending email to jandreu@prhlt.upv.es.
The following information is your real information, for example,
**Group name and acronym:** Just a nickname
**Institution:** Your company or school
**Participants and e-mail:** Yourself and your email
**Contact person:** Yourself
