### ISSUE TITLE
IBME的label的x_rel, y_rel, width, height为什么是浮点数

### ISSUE THREAD

**Issue by qrsssh** [Yuxiang1995/ICDAR2021_MFD#19]
hi, 非常感谢开源 代码及数据集
在用数据集时,发现label中的x_rel, y_rel, width, height都是小数
想问一下这里是做了什么规一化吗,如果想恢复到与原图高宽一致的坐标这里应该如何 处理

**Comment by Yuxiang1995** [comment]
@qrsssh Hello
找到label对应的图片，然后乘上对应原图的宽高即可，可以参考tools/data_preprocess.py
