### ISSUE TITLE
用ResNeSt101多卡训练时梯度爆炸

### ISSUE THREAD

**Issue by hengyeliu** [Yuxiang1995/ICDAR2021_MFD#6]
你好！我按照README里面的ResNeSt101用多卡训练时，一开始就梯度爆炸，请问你有遇到这种情况吗？
![image](https://user-images.githubusercontent.com/37336300/140471617-96d8ab71-d815-4182-b65d-b72f51e7b0c0.png)

**Comment by Yuxiang1995** [comment]
这并不是梯度爆炸，只是用ResNeSt101时防止爆显存而设置的混合精度训练，loss_scale设的dynamic，所以会自适应去改变loss scale，你可以观察一下后续真正的loss是否为Nan

**Comment by ZeroCodePro** [comment]
我按说明用8卡训练，后面loss为nan了，应该怎么调整
