### ISSUE TITLE
请问用resnest50训练后效果很差怎么办？

### ISSUE THREAD

**Issue by Liufangyu** [Yuxiang1995/ICDAR2021_MFD#7]
我是单卡titan xp，batchsize改成了2，然后训练时曾经报错显示不能从float转化为long类型，将一句关于分布式的代码改成直接返回tensor后能够训练了，但是loss一直停留在2左右，出来的结果也不好，可惜您无法提供训练好的模型，我再找找其他的吧。

**Comment by GulpFire** [comment]
请问解决了吗？
